export const dataTemp = [
    {
        id: 1,
        url: 'https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg',
        tipo: 'Automovil',
        placa: 'ABC123',
        marca: 'Toyota',
        modelo: 'Corolla',
        entidad: "México",
        anio: 2013,
        cilindraje: 4,
        serie: 'ABC123',
        motor: 'ABC123',
        tarjeta: 'ABC123',
        seguro: 1,
        tenencia: 2020,
        verificacion: 'Si',
        mantenimiento: 'Si',
        observaciones: 'Ninguna',
    },
    {
        id: 2,
        url: 'https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg',
        tipo: 'Automovil',
        placa: 'ABC123',
        marca: 'Toyota',
        modelo: 'Corolla',
        entidad: "México",
        anio: 2013,
        cilindraje: 4,
        serie: 'ABC123',
        motor: 'ABC123',
        tarjeta: 'ABC123',
        seguro: 1,
        tenencia: 2023,
        verificacion: 'Si',
        mantenimiento: 'Si',
        observaciones: 'Ninguna',
    },
    {
        id: 3,
        url: 'https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg',
        tipo: 'Motocicleta',
        placa: 'ABC124',
        marca: 'Yamaha',
        modelo: 'YBR',
        entidad: "México",
        anio: 2013,
        cilindraje: 4,
        serie: 'ABC124',
        motor: 'ABC124',
        tarjeta: 'ABC124',
        seguro: 1,
        tenencia: 2023,
        verificacion: 'Si',
        mantenimiento: 'Si',
        observaciones: 'Ninguna',
    }
]